name: BarneyScanner
description: "A new Flutter project."
publish_to: "none"
version: 0.1.0

environment:
  sdk: ^3.7.0

dependencies:
  cloud_firestore: ^5.6.5
  cupertino_icons: ^1.0.8
  firebase_auth: ^5.5.1
  firebase_core: ^3.12.1
  firebase_database: 11.3.4
  firebase_storage: ^12.4.4
  flutter:
    sdk: flutter
  get: ^4.7.2
  google_sign_in: ^6.3.0
  image_picker: ^1.1.2
  mobile_scanner: ^6.0.7
  permission_handler: ^11.4.0
  shared_preferences: ^2.5.2

dev_dependencies:
  flutter_test:
    sdk: flutter
  flutter_lints: ^5.0.0

flutter:
  uses-material-design: true
  assets:
    - assets/icon.png
