// File generated by FlutterFire CLI.
// ignore_for_file: type=lint
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        return macos;
      case TargetPlatform.windows:
        return windows;
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyAEe18WRfdn-ymfvth1iUwvvsI9Cm_3Onc',
    appId: '1:891734650498:web:6544881fe0187349ad4e9b',
    messagingSenderId: '891734650498',
    projectId: 'baselogin-e5f57',
    authDomain: 'baselogin-e5f57.firebaseapp.com',
    storageBucket: 'baselogin-e5f57.firebasestorage.app',
    measurementId: 'G-YBQN7M95V0',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyBlfkG5fqw4Av52jMy4f3riBNFM_Mzeyic',
    appId: '1:891734650498:android:10f4775a12035bfaad4e9b',
    messagingSenderId: '891734650498',
    projectId: 'baselogin-e5f57',
    storageBucket: 'baselogin-e5f57.firebasestorage.app',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyD2ngmOIcEkp3EIN2jj9V_ZQ-yEbCNlzeU',
    appId: '1:891734650498:ios:064967ffdfd76360ad4e9b',
    messagingSenderId: '891734650498',
    projectId: 'baselogin-e5f57',
    storageBucket: 'baselogin-e5f57.firebasestorage.app',
    iosBundleId: 'com.example.barneyscanner',
  );

  static const FirebaseOptions macos = FirebaseOptions(
    apiKey: 'AIzaSyD2ngmOIcEkp3EIN2jj9V_ZQ-yEbCNlzeU',
    appId: '1:891734650498:ios:064967ffdfd76360ad4e9b',
    messagingSenderId: '891734650498',
    projectId: 'baselogin-e5f57',
    storageBucket: 'baselogin-e5f57.firebasestorage.app',
    iosBundleId: 'com.example.barneyscanner',
  );

  static const FirebaseOptions windows = FirebaseOptions(
    apiKey: 'AIzaSyAEe18WRfdn-ymfvth1iUwvvsI9Cm_3Onc',
    appId: '1:891734650498:web:df83fe610a3c6c9cad4e9b',
    messagingSenderId: '891734650498',
    projectId: 'baselogin-e5f57',
    authDomain: 'baselogin-e5f57.firebaseapp.com',
    storageBucket: 'baselogin-e5f57.firebasestorage.app',
    measurementId: 'G-7ZY67ND977',
  );
}
